CREATE TABLE IF NOT EXISTS warecare.transaction (
    id int AUTO_INCREMENT PRIMARY KEY NOT NULL,
    date DATE NOT NULL,
    currency SMALLINT NOT NULL,
    code varchar(20) NOT NULL,
    category smallint NOT NULL,
    invoice_to varchar(50) NOT NULL,
    address varchar(255) DEFAULT NULL,
    phone varchar(20) DEFAULT NULL,
    email varchar(50) DEFAULT NULL,
    description varchar(255) DEFAULT NULL,
    qty int(5) NOT NULL,
    price DECIMAL(13,2) NOT NULL,
    tax DECIMAL(13,2) DEFAULT NULL,
    other DECIMAL(13,2) DEFAULT NULL,
    deduction DECIMAL(13,2) DEFAULT NULL,
    paid_by enum('cash','cheque','transfer') NOT NULL,
    status smallint NOT NULL,
    received varchar(50) DEFAULT NULL
);
